### ISSUE TITLE
Bug: the web does not seem to remember login session

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#26] opened 2024-01-24 11:01 UTC
When the user logs in, the web points the user to the main dashboard, which is fine. However, if the user manually types `https://e-rispkp.vercel.app/` in the address bar, the user would be redirected to the login page, while the user is actually already authenticated.

If this happens, the web should have known that the user has already logged in. As such, the dashboard is shown.

**Comment by ahmadzakiakmal** [comment] 2024-01-24 14:20
The issue was resolved in the development environment, but still persists in production (the cookie disappears when visiting the login page in production). Planning to explore and test out workarounds for this issue.

**Comment by ahmadzakiakmal** [comment] 2024-01-25 01:45
Previously, there was a bug preventing users from logging out of the application. However, I've been unable to reproduce this bug recently. Further inspection and additional reports are needed to confirm if the issue still persists. For now, I'm marking this as fixed.

**Closed as completed by ahmadzakiakmal** 2024-01-25 01:45 UTC
Labels: bug, invalid

**Comment by gtrdp** [comment] 2024-01-25 02:32
Just tested and the production environment seems to work as it is suppose to be.

The login page redirects the user to the dashboard, when they are already logged in 🎉.
